---
language: python
python: "2.7"
env:
  matrix:
    - PG_VERSION="9.2"
    - PG_VERSION="9.3"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python-apt python-pycurl
 - sudo service postgresql stop
 - sudo apt-get remove postgresql postgresql-9.1 -qq --purge
install:
  - pip install ansible
script:
  - echo localhost > inventory
  - ansible-playbook --syntax-check -i inventory role.yml
  - ansible-playbook -i inventory role.yml -vvvv --connection=local --sudo --extra-vars="pg_version=$PG_VERSION"
