---
- name: Ensure common packages are installed
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - python-pycurl
  sudo: true
  tags:
    - postgres

- name: Include Ubuntu tasks
  include: ubuntu.yml
  when: not "{{ ansible_distribution }}" != "Ubuntu"

- name: Include Debian tasks
  include: debian.yml
  when: not "{{ ansible_distribution }}" != "Debian"

- name: Ensure apt cache is up to date
  apt: update_cache=yes
  sudo: true

- name: Ensure packages are installed
  apt: pkg={{ item }}
  with_items:
    - postgresql-{{ pg_version }}
    - postgresql-client-{{ pg_version }}
    - python-psycopg2
  register: db_setup
  environment: pg_proxy_env
  sudo: true
  tags:
    - postgres

- name: Recreate cluster
  include: recreate_cluster.yml
  when: pg_cluster_recreate

- name: Update pg_hba.conf file
  template: src=pg_hba.conf.j2 dest=/etc/postgresql/{{ pg_version }}/{{ pg_cluster }}/pg_hba.conf owner={{ pg_admin_user }} group={{ pg_admin_user }} mode=0640
  notify: restart postgresql
  sudo: true
  tags:
    - postgres

- name: Update postgres.conf file
  template: src=master.conf.j2 dest=/etc/postgresql/{{ pg_version }}/{{ pg_cluster }}/postgresql.conf owner={{ pg_admin_user }} group={{ pg_admin_user }} mode=0644
  sudo: true
  notify: restart postgresql
  tags:
    - postgres

- meta: flush_handlers

- name: ensure postgresql server is started
  service: name=postgresql state=started enabled=yes arguments={{ pg_version }} pattern="/{{ pg_version }}/.*/postgres"
  sudo: true
  tags:
    - postgres

- include: extensions_common.yml

- include: postgis.yml
  when: pg_postgis
